/*
 * File: app/store/Scores.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OneClick.store.Scores', {
    extend: 'Ext.data.Store',
    alias: 'store.scores',

    requires: [
        'OneClick.model.Score'
    ],

    config: {
        model: 'OneClick.model.Score',
        storeId: 'ScoreStore'
    }
});