/*
 * File: app/view/AppInitContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OneClick.view.AppInitContainer', {
    extend: 'Ext.Container',
    alias: 'widget.appinitcontainer',

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'container',
                flex: 0.5,
                items: [
                    {
                        xtype: 'label',
                        docked: 'bottom',
                        html: '<center>OneClick</center>',
                        ui: '',
                        width: '100%'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 0.5
            }
        ]
    }

});