/*
 * File: app/view/CampaignListContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OneClick.view.CampaignListContainer', {
    extend: 'Ext.Container',
    alias: 'widget.campaignlistcontainer',

    requires: [
        'OneClick.view.ActiveCampaignList',
        'OneClick.view.SuccessCampaignList',
        'OneClick.view.UnsuccessCampaignList',
        'OneClick.view.InactiveCampaignList'
    ],

    config: {
        layout: {
            align: 'start',
            type: 'vbox'
        },
        scrollable: true,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'headerBar',
                title: 'Home',
                layout: {
                    align: 'center',
                    pack: 'end',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'image',
                        docked: 'left',
                        itemId: 'avatar',
                        width: 50
                    },
                    {
                        xtype: 'button',
                        itemId: 'btnNavigation',
                        iconAlign: 'right',
                        iconCls: 'bookmarks'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 30,
                itemId: 'pageContainer',
                margin: '0.3em 0',
                width: '100%',
                items: [
                    {
                        xtype: 'label',
                        docked: 'left',
                        itemId: 'pageTitle',
                        margin: '0 0 0 0.3em',
                        style: 'line-height:30px'
                    },
                    {
                        xtype: 'image',
                        docked: 'right',
                        height: 30,
                        itemId: 'pageAvatar',
                        margin: '0 0.3em 0 0',
                        width: 30
                    }
                ]
            },
            {
                xtype: 'activecampaignlist',
                margin: '5 10'
            },
            {
                xtype: 'successcampaignlist',
                margin: '5 10'
            },
            {
                xtype: 'unsuccesscampaignlist',
                margin: '5 10'
            },
            {
                xtype: 'inactivecampaignlist',
                margin: '5 10'
            }
        ]
    }

});