/*
 * File: app/view/ProfileContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('OneClick.view.ProfileContainer', {
    extend: 'Ext.Container',
    alias: 'widget.profilecontainer',

    config: {
        scrollable: true,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Profile',
                layout: {
                    pack: 'end',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'btnNavigation',
                        iconAlign: 'right',
                        iconCls: 'bookmarks'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'settings',
                title: 'Settings',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'name',
                        label: 'Name',
                        name: 'name',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'email',
                        label: 'Email',
                        name: 'email',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'fieldset'
            }
        ]
    }

});